"""Train the HRM thinker and one-shot baselines on synthetic multi-cause inference (0-3
simultaneous causes, explaining away), then evaluate.

    python scripts/train_thinker_multicause.py                        # full run (~20 min, RTX 5060)
    python scripts/train_thinker_multicause.py train.steps=200 train.baseline_steps=200 eval.n=1000

Writes <out_dir>/multicause_eval.json, multicause_eval.md, train_multicause_<model>.jsonl,
checkpoints/multicause_<model>.pt.
"""

import argparse
import json
import sys
import time
from pathlib import Path

import torch

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from pai.config import REPO_ROOT, load_config  # noqa: E402
from pai.thinker.evaluate import evaluate_multicause, overlap_sweep, teacher_reference_multicause  # noqa: E402
from pai.thinker.multicause import CAUSE_LIB, MultiCauseConfig, MultiCauseTask  # noqa: E402
from pai.thinker.train import build_model, multicause_loss, n_params, train_thinker  # noqa: E402
from pai.train.common import JsonlLogger, save_checkpoint  # noqa: E402


def _pct(v: float) -> str:
    return f"{100 * v:.1f}%"


def write_markdown(res: dict, path: Path) -> None:
    t, models = res["teacher"]["overall"], res["models"]
    lines = ["# HRM thinker: synthetic multi-cause inference (explaining away)", "",
             f"{len(CAUSE_LIB)}-cause library, 0-{res['config']['task']['max_active']} simultaneous causes, "
             f"exact Bayesian subset teacher, {res['eval_n']} test examples. "
             f"Generated by `scripts/train_thinker_multicause.py`.", "",
             "| Model | Params | Train time | Exact-subset acc | Per-cause acc | Subset agree w/ teacher | "
             "KL(subset) | Marginal BCE(teacher) | Mean segments |",
             "|---|---|---|---|---|---|---|---|---|",
             f"| exact teacher | - | - | {_pct(t['exact_subset_acc'])} | {_pct(t['per_cause_acc'])} | 100% | 0 | 0 | - |"]
    for name, m in models.items():
        o = m["eval"]["overall"]
        lines.append(f"| {name} | {m['params'] / 1e6:.2f}M | {m['train']['wall_s'] / 60:.1f} min | "
                     f"{_pct(o['exact_subset_acc'])} | {_pct(o['per_cause_acc'])} | {_pct(o['subset_teacher_agree'])} | "
                     f"{o['kl_subset_to_teacher']:.4f} | {o['marginal_bce_to_teacher']:.4f} | {m['eval']['mean_segments']:.2f} |")

    hrm = models.get("hrm", {}).get("eval")
    if hrm:
        lines += ["", "## Thinking segments vs difficulty (HRM, learned halting)", ""]
        d = hrm["difficulty"]["n_active_causes"]
        lines += [f"**number of simultaneous causes** (Spearman with segments used: {d['spearman_segments']:+.3f})", "",
                  "| # active causes | n | Mean segments | Exact-subset acc | Per-cause acc | Subset agree |",
                  "|---|---|---|---|---|---|"]
        for b in d["bins"]:
            lines.append(f"| {b['n_active']} | {b['n']} | {b['mean_segments']:.2f} | {_pct(b['exact_subset_acc'])} | "
                         f"{_pct(b['per_cause_acc'])} | {_pct(b['subset_teacher_agree'])} |")
        lines.append("")
        for key in ("teacher_subset_entropy", "noise_sigma", "evidence_length"):
            d = hrm["difficulty"][key]
            lines += [f"**{key}** (Spearman with segments used: {d['spearman_segments']:+.3f})", "",
                      "| Bin | n | Mean segments | Exact-subset acc | Per-cause acc | Subset agree |", "|---|---|---|---|---|---|"]
            for b in d["bins"]:
                lines.append(f"| {b['range'][0]:.3g}-{b['range'][1]:.3g} | {b['n']} | {b['mean_segments']:.2f} | "
                             f"{_pct(b['exact_subset_acc'])} | {_pct(b['per_cause_acc'])} | {_pct(b['subset_teacher_agree'])} |")
            lines.append("")
        lines += ["## Accuracy vs thinking budget (HRM)", "",
                  "| Max segments | Halting: exact-subset acc | Halting: KL(subset) | Halting: mean segs | "
                  "Forced: exact-subset acc | Forced: KL(subset) |",
                  "|---|---|---|---|---|---|"]
        for b in hrm["budget"]:
            h, f = b["halting"], b["forced"]
            lines.append(f"| {b['max_segments']} | {_pct(h['exact_subset_acc'])} | {h['kl_subset_to_teacher']:.4f} | "
                         f"{h['mean_segments']:.2f} | {_pct(f['exact_subset_acc'])} | {f['kl_subset_to_teacher']:.4f} |")
        lines += ["", f"Segment histogram (1..max): {hrm['segment_histogram']}"]
        if "overlap_sweep" in res:
            lines += ["", "## Overlap sweep (eval-only, same trained HRM; overlap is a fixed task knob, not a nuisance)", "",
                      "| Overlap | Mean segments | Student exact-subset acc | Teacher exact-subset acc | Student KL(subset) |",
                      "|---|---|---|---|---|"]
            for row in res["overlap_sweep"]:
                lines.append(f"| {row['overlap']} | {row['mean_segments']:.2f} | {_pct(row['student']['exact_subset_acc'])} | "
                             f"{_pct(row['teacher']['exact_subset_acc'])} | {row['student']['kl_subset_to_teacher']:.4f} |")
    lines += ["", "## Speed (examples/second, GPU)", "",
              "| Model | Thinker, batched | Teacher, batched | Thinker, batch 1 | Teacher, batch 1 |", "|---|---|---|---|---|"]
    for name, m in models.items():
        s = m["eval"]["speed"]
        lines.append(f"| {name} | {s['batched']['thinker_ex_per_s']:.0f} | {s['batched']['teacher_ex_per_s']:.0f} | "
                     f"{s['batch1']['thinker_ex_per_s']:.0f} | {s['batch1']['teacher_ex_per_s']:.0f} |")
    path.write_text("\n".join(lines) + "\n")


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--config", default=str(REPO_ROOT / "configs" / "thinker_multicause.yaml"))
    ap.add_argument("overrides", nargs="*", help="config overrides, e.g. train.steps=200")
    args = ap.parse_args()
    cfg = load_config(args.config, args.overrides)
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    torch.manual_seed(cfg.seed)
    out = Path(cfg.out_dir) if Path(cfg.out_dir).is_absolute() else REPO_ROOT / cfg.out_dir
    out.mkdir(parents=True, exist_ok=True)
    task_cfg = MultiCauseConfig.from_dict(cfg.task.to_dict())
    task = MultiCauseTask(task_cfg, device)
    print(f"multi-cause teacher bank: {task.n_combos} (subset, nuisance) templates")
    gen = torch.Generator(device).manual_seed(cfg.seed + 12345)  # test set independent of training draws
    data = task.sample(cfg.eval.n, gen)
    res = {"config": cfg.to_dict(), "eval_n": cfg.eval.n,
           "device": torch.cuda.get_device_name(0) if device.type == "cuda" else "cpu",
           "teacher": teacher_reference_multicause(data), "models": {}}
    t_all = time.time()
    for kind in cfg.models:
        torch.manual_seed(cfg.seed)
        model = build_model(kind, task, cfg.model.to_dict())
        tcfg = cfg.train.to_dict()
        if kind != "hrm":
            tcfg["steps"] = tcfg["baseline_steps"]
        log_path = out / f"train_multicause_{kind}.jsonl"
        log_path.unlink(missing_ok=True)
        print(f"== {kind}: {n_params(model) / 1e6:.2f}M params")
        info = train_thinker(model, task, tcfg, device, JsonlLogger(log_path), seed=cfg.seed, loss_fn=multicause_loss)
        save_checkpoint(out / "checkpoints" / f"multicause_{kind}.pt",
                        {"kind": kind, "model": model.state_dict(), "config": cfg.to_dict()})
        ev = evaluate_multicause(model, task, data, device, cfg.eval.to_dict())
        res["models"][kind] = {"params": n_params(model), "train": info, "eval": ev}
        print(f"   {kind}: {json.dumps(ev['overall'])}  segments={ev['mean_segments']:.2f}  train {info['wall_s']:.0f}s")
        if kind == "hrm":
            res["overlap_sweep"] = overlap_sweep(model, task_cfg, device, cfg.eval.overlap_n, cfg.eval.batch,
                                                 list(cfg.eval.overlaps))
    res["total_wall_s"] = round(time.time() - t_all, 1)
    (out / "multicause_eval.json").write_text(json.dumps(res, indent=2))
    write_markdown(res, out / "multicause_eval.md")
    print(f"wrote {out / 'multicause_eval.json'} and multicause_eval.md ({res['total_wall_s'] / 60:.1f} min)")


if __name__ == "__main__":
    main()
