"""Train the HRM thinker and one-shot baselines on synthetic cause inference, then evaluate.

    python scripts/train_thinker_synthetic.py                         # full run (~15 min, RTX 5060)
    python scripts/train_thinker_synthetic.py train.steps=200 train.baseline_steps=200 eval.n=2000

Writes <out_dir>/synthetic_eval.json, synthetic_eval.md, train_<model>.jsonl, checkpoints/<model>.pt.
"""

import argparse
import json
import sys
import time
from pathlib import Path

import torch

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from pai.config import REPO_ROOT, load_config  # noqa: E402
from pai.thinker.evaluate import evaluate_thinker, teacher_reference  # noqa: E402
from pai.thinker.synthetic import CAUSES, CauseTask, TaskConfig  # noqa: E402
from pai.thinker.train import build_model, n_params, train_thinker  # noqa: E402
from pai.train.common import JsonlLogger, save_checkpoint  # noqa: E402


def _pct(v: float) -> str:
    return f"{100 * v:.1f}%"


def write_markdown(res: dict, path: Path) -> None:
    t, models = res["teacher"]["overall"], res["models"]
    lines = ["# HRM thinker: synthetic cause inference", "",
             f"{len(CAUSES)} causes, exact Bayesian teacher, {res['eval_n']} test examples. "
             f"Generated by `scripts/train_thinker_synthetic.py`.", "",
             "| Model | Params | Train time | Acc (true cause) | Agree w/ teacher | KL to teacher | ECE | Mean segments |",
             "|---|---|---|---|---|---|---|---|",
             f"| exact teacher | - | - | {_pct(t['acc'])} | 100% | 0 | {t['ece']:.3f} | - |"]
    for name, m in models.items():
        o = m["eval"]["overall"]
        lines.append(f"| {name} | {m['params'] / 1e6:.2f}M | {m['train']['wall_s'] / 60:.1f} min | {_pct(o['acc'])} | "
                     f"{_pct(o['teacher_agree'])} | {o['kl_to_teacher']:.4f} | {o['ece']:.3f} | {m['eval']['mean_segments']:.2f} |")
    hrm = models.get("hrm", {}).get("eval")
    if hrm:
        lines += ["", "## Thinking segments vs difficulty (HRM, learned halting)", ""]
        for key, d in hrm["difficulty"].items():
            lines += [f"**{key}** (Spearman with segments used: {d['spearman_segments']:+.3f})", "",
                      "| Bin | n | Mean segments | HRM acc | Teacher acc | Agree |", "|---|---|---|---|---|---|"]
            for b in d["bins"]:
                lines.append(f"| {b['range'][0]:.3g}-{b['range'][1]:.3g} | {b['n']} | {b['mean_segments']:.2f} | "
                             f"{_pct(b['acc'])} | {_pct(b['teacher_acc'])} | {_pct(b['teacher_agree'])} |")
            lines.append("")
        lines += ["## Accuracy vs thinking budget (HRM)", "",
                  "| Max segments | Halting: acc | Halting: KL | Halting: mean segs | Forced: acc | Forced: KL |",
                  "|---|---|---|---|---|---|"]
        for b in hrm["budget"]:
            h, f = b["halting"], b["forced"]
            lines.append(f"| {b['max_segments']} | {_pct(h['acc'])} | {h['kl_to_teacher']:.4f} | {h['mean_segments']:.2f} | "
                         f"{_pct(f['acc'])} | {f['kl_to_teacher']:.4f} |")
        lines += ["", f"Segment histogram (1..max): {hrm['segment_histogram']}"]
        if "heldout_cause" in hrm:
            h = hrm["heldout_cause"]
            lines += ["", f"Held-out cause (not in the teacher's library): HRM mean max-prob {h['mean_max_prob']:.3f} "
                      f"vs {h['mean_max_prob_known']:.3f} on known causes; teacher "
                      f"{res['teacher']['heldout_cause']['mean_max_prob']:.3f}; HRM segments {h['mean_segments']:.2f}."]
    lines += ["", "## Speed (examples/second, GPU)", "", "| Model | Thinker, batched | Teacher, batched | Thinker, batch 1 | Teacher, batch 1 |",
              "|---|---|---|---|---|"]
    for name, m in models.items():
        s = m["eval"]["speed"]
        lines.append(f"| {name} | {s['batched']['thinker_ex_per_s']:.0f} | {s['batched']['teacher_ex_per_s']:.0f} | "
                     f"{s['batch1']['thinker_ex_per_s']:.0f} | {s['batch1']['teacher_ex_per_s']:.0f} |")
    path.write_text("\n".join(lines) + "\n")


def main() -> None:
    # Own parser (not scripts/_cli.py) so the default config is thinker.yaml.
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--config", default=str(REPO_ROOT / "configs" / "thinker.yaml"))
    ap.add_argument("overrides", nargs="*", help="config overrides, e.g. train.steps=200")
    args = ap.parse_args()
    cfg = load_config(args.config, args.overrides)
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    torch.manual_seed(cfg.seed)
    out = Path(cfg.out_dir) if Path(cfg.out_dir).is_absolute() else REPO_ROOT / cfg.out_dir
    out.mkdir(parents=True, exist_ok=True)
    task = CauseTask(TaskConfig.from_dict(cfg.task.to_dict()), device)
    gen = torch.Generator(device).manual_seed(cfg.seed + 12345)  # test set independent of training draws
    data = task.sample(cfg.eval.n, gen, heldout_prob=0.0)
    heldout = task.sample(cfg.eval.heldout_n, gen, heldout_prob=1.0)
    res = {"config": cfg.to_dict(), "eval_n": cfg.eval.n, "device": torch.cuda.get_device_name(0) if device.type == "cuda" else "cpu",
           "teacher": teacher_reference(task, data, heldout), "models": {}}
    t_all = time.time()
    for kind in cfg.models:
        torch.manual_seed(cfg.seed)
        model = build_model(kind, task, cfg.model.to_dict())
        tcfg = cfg.train.to_dict()
        if kind != "hrm":
            tcfg["steps"] = tcfg["baseline_steps"]
        log_path = out / f"train_{kind}.jsonl"
        log_path.unlink(missing_ok=True)
        print(f"== {kind}: {n_params(model) / 1e6:.2f}M params")
        info = train_thinker(model, task, tcfg, device, JsonlLogger(log_path), seed=cfg.seed)
        save_checkpoint(out / "checkpoints" / f"{kind}.pt", {"kind": kind, "model": model.state_dict(), "config": cfg.to_dict()})
        ev = evaluate_thinker(model, task, data, device, cfg.eval.to_dict(), heldout)
        res["models"][kind] = {"params": n_params(model), "train": info, "eval": ev}
        print(f"   {kind}: {json.dumps(ev['overall'])}  segments={ev['mean_segments']:.2f}  train {info['wall_s']:.0f}s")
    res["total_wall_s"] = round(time.time() - t_all, 1)
    (out / "synthetic_eval.json").write_text(json.dumps(res, indent=2))
    write_markdown(res, out / "synthetic_eval.md")
    print(f"wrote {out / 'synthetic_eval.json'} and synthetic_eval.md ({res['total_wall_s'] / 60:.1f} min)")


if __name__ == "__main__":
    main()
